# =========================
# Experiment Config: Text-RGCN
# =========================

output:
  exp_name: text_rgcn

dataset:
  train: data/datasets/openbg500/raw/OpenBG500-L_train.tsv
  dev: data/datasets/openbg500/raw/OpenBG500-L_dev.tsv
  test: data/datasets/openbg500/raw/OpenBG500-L_test.tsv
  cache_dir: data/cache/openbg500

model:
  name: text_rgcn
  num_relations: 500
  num_entities: 2782223
  text_emb_dim: 768
  hidden_dim: 256
  num_layers: 2
  num_bases: 8
  sample_neighbors: 10
  dropout: 0.1

training:
  batch_size: 512
  neg_ratio: 5

system:
  deterministic: true
