# =========================
# Experiment Config: OpenBG-IMG Gated Fusion
# =========================

dataset:
  name: openbg_img
  train: datasets/openbg_img/raw/OpenBG-IMG_train.tsv
  dev: datasets/openbg_img/raw/OpenBG-IMG_dev.tsv
  test: datasets/openbg_img/raw/OpenBG-IMG_test.tsv
  cache_dir: cache/openbg_img

model:
  name: openbg_img_gated
  num_relations: 136
  use_layernorm: true

output:
  exp_name: openbg_img_gated